site_name: PyTypes Documentation
repo_url: https://github.com/pvs-hd-tea/PyTypes
site_dir: site
edit_uri : edit/main/docs
nav:
  - Home: index.md
  - About: about.md
  - Workflow:
    - Fetching: workflow/fetching.md
    - Tracing: workflow/tracing.md
    - Annotating: workflow/annotating.md
    - Evaluating: workflow/evaluating.md
  - Pyramid: pyramid.md

theme: material  # readthedocs  mkdocs

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true