site_name: PyTypes Documentation
repo_url: https://github.com/pvs-hd-tea/PyTypes
site_dir: site
edit_uri : edit/gh-pages/docs
nav:
  - Home: index.md
  - About: about.md

  - Workflow:
    - Fetching: workflow/fetching.md
    - Tracing: workflow/tracing.md
    - Annotating: workflow/annotating.md
    - Evaluating: workflow/evaluating.md

  
  - Misc:
    - Configuration: misc/config.md
    - Types, Modules & Qualified Names: misc/resolver.md

  - API:
    - Fetching: api/fetching.md
    - Tracing: api/tracing.md
    - Annotating: api/typegen.md
    - Evaluation: api/evaluation.md

theme: material  # readthedocs  mkdocs

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [common, fetching, tracing, typegen, evaluation]  # search packages in the src folder
          options:
            docstring_style: sphinx
            show_source: false

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true