unifier = []

[pytypes]
project = "repo"
stdlib_path = "/usr/lib/python3.10"
proj_path = "/home/secret/project-dir"
venv_path = "/home/secret/.cache/pypoetry/virtualenvs/pytypes-xvtnrWJT-py3.10"
benchmark_performance = false
