name: Lint Code Base

on:
  pull_request:
    types:
      - closed

jobs:
  linting:
    if: github.event.pull_request.merged == true
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
      fetch-depth: 1

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}